# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check branch
        if: $GITHUB_REF != 'refs/heads/main'
        run: |
          echo "Workflow is only supported for 'refs/heads/main'. Current branch is $GITHUB_REF"
          exit 1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.CI_TOKEN}}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          server-id: ossrh
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{secrets.GPG_PRIVATE_KEY}}

      - name: Release
        run: |
          git config user.email ci@users.noreply.github.com
          git config user.name ci
          mvn -B release:clean release:prepare --file pom.xml
          mvn -B release:perform --file pom.xml
        env:
          SERVER_USERNAME: ${{secrets.OSSRH_USERNAME}}
          SERVER_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
